
BEGIN {
    FS = "\n"
    print "## This file is generated by the script 'make_err.awk'."
    print "## Do not edit by hand.\n\n"
}
/@export/ {
    print $0
}
/@rdname/ {
    print $0
    printed_rdname = 1
}   
/<- function/ {
    has_equals = index($1, "=") > 0
    if (has_equals) {
	print "function definition appears to include a default value : ", $1 | "cat 1>&2"
	exit 1
    }
    split($1, a, " <- ")
    if (!printed_rdname)
	print "#' @rdname", a[1]
    printed_rdname = 0
    gsub("^chk", "err", $1)
    print $1
    gsub("^err", "chk", $1)
    gsub(" <- function", "", $1)
    gsub(" {", "", $1)
    printf("    val <- %s\n", $1)
    print "    if (is.character(val))"
    print "        stop(val, call. = FALSE)"
    print "    TRUE"
    print "}\n"	
}

