
BEGIN {
    FS = " <- "
    print "## This file is generated by the script 'make_err.awk'."
    print "## Do not edit by hand.\n\n"
}
NR == 1 {
    help_name = substr(FILENAME, 7)
    sub("\\.R", "", help_name)
}
/<- function/ {
    base_name = substr($1, 5)
    args = substr($2, 9)
    sub(" {", "", args)
    print "#' @export"
    printf("#' @rdname %s\n", help_name)
    printf("err_%s <- %s\n", base_name, $2)
    printf("    val <- chk_%s%s\n", base_name, args)
    print "    if (is.character(val))"
    print "        stop(val, call. = FALSE)"
    print "    TRUE"
    print "}\n"	
}
