## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname chk_trans_list
err_trans_list <- function(x, name) {
    val <- chk_trans_list(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

