## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname chk_all_0_1
err_all_0_1 <- function(x, name) {
    val <- chk_all_0_1(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_character
err_is_character <- function(x, name) {
    val <- chk_is_character(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_date
err_is_date <- function(x, name) {
    val <- chk_is_date(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_date_equiv
err_is_date_equiv_scalar <- function(x, name) {
    val <- chk_is_date_equiv_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_date_equiv
err_is_date_equiv_vector <- function(x, name) {
    val <- chk_is_date_equiv_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_date_or_numeric
err_is_date_or_numeric <- function(x, name) {
    val <- chk_is_date_or_numeric(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_is_na
#' @export
err_is_na_scalar <- function(x, name) {
    val <- chk_is_na_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_is_na
#' @export
err_is_na_vector <- function(x, name) {
    val <- chk_is_na_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_finite_scalar
err_finite_scalar <- function(x, name) {
    val <- chk_finite_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_finite_scalar
err_finite_vector <- function(x, name) {
    val <- chk_finite_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_has_non_na
err_has_non_na <- function(x, name) {
    val <- chk_has_non_na(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_has_nonzero
err_has_nonzero <- function(x, name) {
    val <- chk_has_nonzero(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_is_integer
#' @export
err_is_integer <- function(x, name) {
    val <- chk_is_integer(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_integer
err_is_integer_consec <- function(x, name) {
    val <- chk_is_integer_consec(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_integer_equiv
err_is_integer_equiv_scalar <- function(x, name) {
    val <- chk_is_integer_equiv_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_integer_equiv
err_is_integer_equiv_vector <- function(x, name) {
    val <- chk_is_integer_equiv_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_numeric
err_is_numeric <- function(x, name) {
    val <- chk_is_numeric(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_length_1
err_length_1 <- function(x, name) {
    val <- chk_length_1(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_logical
err_is_logical <- function(x, name) {
    val <- chk_is_logical(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_not_blank
#' @export
err_not_blank_scalar <- function(x, name) {
    val <- chk_not_blank_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_not_blank
#' @export
err_not_blank_vector <- function(x, name) {
    val <- chk_not_blank_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_not_na
err_not_na_dataframe <- function(x, name) {
    val <- chk_not_na_dataframe(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_not_na
err_not_na_list <- function(x, name) {
    val <- chk_not_na_list(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_not_na
err_not_na_scalar <- function(x, name) {
    val <- chk_not_na_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_not_na
err_not_na_vector <- function(x, name) {
    val <- chk_not_na_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_positive_length
err_positive_length <- function(x, name) {
    val <- chk_positive_length(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_no_dimnames
err_no_dimnames <- function(x, name) {
    val <- chk_no_dimnames(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_no_names
err_no_names <- function(x, name) {
    val <- chk_no_names(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_nonzero_unique
err_nonzero_unique <- function(x, name) {
    val <- chk_nonzero_unique(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

