## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname composite
err_ge_age_min <- function(age, age_min, date, dob, unit) {
    val <- chk_ge_age_min(age, age_min, date, dob, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_lt_age_max <- function(age, age_max, date, dob, unit) {
    val <- chk_lt_age_max(age, age_max, date, dob, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_all_class <- function(x, name, class) {
    val <- chk_all_class(x, name, class)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_array_metadata_complete <- function(x, name) {
    val <- chk_array_metadata_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_character_complete <- function(x, name) {
    val <- chk_character_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_dimnames_complete <- function(x, name) {
    val <- chk_dimnames_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_first_day_unit <- function(x, name, unit) {
    val <- chk_is_first_day_unit(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_first_day_unit_consec <- function(x, name, unit) {
    val <- chk_is_first_day_unit_consec(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_ge_scalar <- function(x1, x2, name1, name2) {
    val <- chk_is_ge_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_ge_vector <- function(x1, x2, name1, name2) {
    val <- chk_is_ge_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_gt_scalar <- function(x1, x2, name1, name2) {
    val <- chk_is_gt_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_gt_vector <- function(x1, x2, name1, name2) {
    val <- chk_is_gt_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_integer_consec <- function(x, name) {
    val <- chk_is_integer_consec(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_logical_flag <- function(x, name) {
    val <- chk_is_logical_flag(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_multiple_of <- function(x1, x2, name1, name2) {
    val <- chk_is_multiple_of(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_non_negative_scalar <- function(x, name) {
    val <- chk_is_non_negative_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_non_negative_vector <- function(x, name) {
    val <- chk_is_non_negative_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_positive_scalar <- function(x, name) {
    val <- chk_is_positive_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_positive_vector <- function(x, name) {
    val <- chk_is_positive_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_string <- function(x, name) {
    val <- chk_is_string(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_strictly_increasing <- function(x, name) {
    val <- chk_is_strictly_increasing(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_length_same <- function(x1, x2, name1, name2) {
    val <- chk_length_same(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_length_same_or_1 <- function(x1, x2, name1, name2) {
    val <- chk_length_same_or_1(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_names_complete <- function(x, name) {
    val <- chk_names_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_names_dimnames_complete <- function(x, name) {
    val <- chk_names_dimnames_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_trans_list <- function(x, name) {
    val <- chk_trans_list(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

