## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname composite
err_all_class <- function(x, name, class) {
    val <- chk_all_class(x, name, class)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_array_metadata_complete <- function(x, name) {
    val <- chk_array_metadata_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_break_min_max_date <- function(break_min, break_max, unit) {
    val <- chk_break_min_max_date(break_min, break_max, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_character_complete <- function(x, name) {
    val <- chk_character_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_date_consistent_with_month_start <- function(x, name, month_start) {
    val <- chk_date_consistent_with_month_start(x, name, month_start)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_date_consistent_with_width_origin <- function(x, name, origin, width) {
    val <- chk_date_consistent_with_width_origin(x, name, origin, width)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_dimnames_complete <- function(x, name) {
    val <- chk_dimnames_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_dimtypes_mutually_compatible <- function(dimtypes) {
    val <- chk_dimtypes_mutually_compatible(dimtypes)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_dimtypes_pairs_complete <- function(names) {
    val <- chk_dimtypes_pairs_complete(names)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_dimtypes_pairs_suffix <- function(dimtypes, names) {
    val <- chk_dimtypes_pairs_suffix(dimtypes, names)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_ge_break_min_age <- function(age, break_min, date, dob, unit) {
    val <- chk_ge_break_min_age(age, break_min, date, dob, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_ge_break_min_date <- function(date, break_min) {
    val <- chk_ge_break_min_date(date, break_min)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_first_day_unit_scalar <- function(x, name, unit) {
    val <- chk_is_first_day_unit_scalar(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_first_day_unit_vector <- function(x, name, unit) {
    val <- chk_is_first_day_unit_vector(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_first_day_unit_consec <- function(x, name, unit) {
    val <- chk_is_first_day_unit_consec(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_ge_scalar <- function(x1, x2, name1, name2) {
    val <- chk_is_ge_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_ge_vector <- function(x1, x2, name1, name2) {
    val <- chk_is_ge_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_gt_scalar <- function(x1, x2, name1, name2) {
    val <- chk_is_gt_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_gt_vector <- function(x1, x2, name1, name2) {
    val <- chk_is_gt_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_integer_consec <- function(x, name) {
    val <- chk_is_integer_consec(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_logical_flag <- function(x, name) {
    val <- chk_is_logical_flag(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_multiple_of <- function(x1, x2, name1, name2, null_ok) {
    val <- chk_is_multiple_of(x1, x2, name1, name2, null_ok)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_multiple_of_n <- function(x, name, n, null_ok) {
    val <- chk_is_multiple_of_n(x, name, n, null_ok)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_non_negative_scalar <- function(x, name) {
    val <- chk_is_non_negative_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_non_negative_vector <- function(x, name) {
    val <- chk_is_non_negative_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_positive_scalar <- function(x, name) {
    val <- chk_is_positive_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_positive_vector <- function(x, name) {
    val <- chk_is_positive_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_string <- function(x, name) {
    val <- chk_is_string(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_strictly_increasing <- function(x, name) {
    val <- chk_is_strictly_increasing(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_is_valid_quantile <- function(x, name) {
    val <- chk_is_valid_quantile(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_labels_valid_for_dimtype <- function(labels, dimtype) {
    val <- chk_labels_valid_for_dimtype(labels, dimtype)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_length_same <- function(x1, x2, name1, name2) {
    val <- chk_length_same(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_length_same_or_1 <- function(x1, x2, name1, name2) {
    val <- chk_length_same_or_1(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_lt_break_max_age <- function(age, break_max, date, dob, unit) {
    val <- chk_lt_break_max_age(age, break_max, date, dob, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_lt_break_max_date <- function(date, break_max) {
    val <- chk_lt_break_max_date(date, break_max)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_names_complete <- function(x, name) {
    val <- chk_names_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_names_dimnames_complete <- function(x, name) {
    val <- chk_names_dimnames_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_trans_list <- function(x, name) {
    val <- chk_trans_list(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_x_integer <- function(x, name, open_first, open_last) {
    val <- chk_x_integer(x, name, open_first, open_last)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname composite
err_x_min_max_integer <- function(x_min, x_max, name_min, name_max) {
    val <- chk_x_min_max_integer(x_min, x_max, name_min, name_max)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

