## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname chk_age_label_ge_break_min
err_age_label_ge_break_min <- function(labels, age_low, break_min) {
    val <- chk_age_label_ge_break_min(labels, age_low, break_min)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_age_label_ge_break_min
err_age_label_le_break_max <- function(labels, age_up, break_max) {
    val <- chk_age_label_le_break_max(labels, age_up, break_max)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_age_diff_gt_one
err_age_diff_gt_one <- function(age_low, age_up, is_low_up, labels) {
    val <- chk_age_diff_gt_one(age_low, age_up, is_low_up, labels)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_all_x1_in_x2
err_all_x1_in_x2 <- function(x1, x2, name1, name2, exclude_zero) {
    val <- chk_all_x1_in_x2(x1, x2, name1, name2, exclude_zero)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_array_metadata_complete
err_array_metadata_complete <- function(x, name) {
    val <- chk_array_metadata_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_character_complete
err_character_complete <- function(x, name) {
    val <- chk_character_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_difference_divisible
err_difference_divisible <- function(x1, x2, y, name1, name2, name_y) {
    val <- chk_difference_divisible(x1, x2, y, name1, name2, name_y)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_dim_min_length
err_dim_min_length <- function(length_actual, length_min, name) {
    val <- chk_dim_min_length(length_actual, length_min, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_intervals_inside_breaks
err_intervals_inside_breaks <- function(age_low, age_up, breaks, labels) {
    val <- chk_intervals_inside_breaks(age_low, age_up, breaks, labels)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_omitted
#' @export
err_omitted <- function(index, map_dim, name_index, name_dim) {
    val <- chk_omitted(index, map_dim, name_index, name_dim)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_omitted
#' @export
err_not_omitted <- function(index, map_dim, name_index, name_dim) {
    val <- chk_not_omitted(index, map_dim, name_index, name_dim)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_dimnames_complete
err_dimnames_complete <- function(x, name) {
    val <- chk_dimnames_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_dimtypes_mutually_compatible
err_dimtypes_mutually_compatible <- function(dimtypes) {
    val <- chk_dimtypes_mutually_compatible(dimtypes)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_integer_in_range
err_integer_in_range <- function(x, min, max, name) {
    val <- chk_integer_in_range(x, min, max, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_names_pairs_complete
err_names_pairs_complete <- function(names) {
    val <- chk_names_pairs_complete(names)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_names_pairs_suffix
err_names_pairs_suffix <- function(dimtypes, names) {
    val <- chk_names_pairs_suffix(dimtypes, names)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_ge_break_min_age
err_ge_break_min_age <- function(age, break_min, date, dob, unit) {
    val <- chk_ge_break_min_age(age, break_min, date, dob, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_ge_break_min_date
err_ge_break_min_date <- function(date, break_min) {
    val <- chk_ge_break_min_date(date, break_min)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_class
err_is_class_obj <- function(x, name, class) {
    val <- chk_is_class_obj(x, name, class)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_class
err_is_class_list <- function(x, name, class) {
    val <- chk_is_class_list(x, name, class)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_first_day_unit_scalar
err_first_day_unit_scalar <- function(x, name, unit) {
    val <- chk_first_day_unit_scalar(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_first_day_unit_scalar
err_first_day_unit_vector <- function(x, name, unit) {
    val <- chk_first_day_unit_vector(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_first_day_unit_scalar
err_first_day_unit_consec <- function(x, name, unit) {
    val <- chk_first_day_unit_consec(x, name, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_ge
err_ge_scalar <- function(x1, x2, name1, name2) {
    val <- chk_ge_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_ge
err_ge_vector <- function(x1, x2, name1, name2) {
    val <- chk_ge_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_gt
err_gt_scalar <- function(x1, x2, name1, name2) {
    val <- chk_gt_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_gt
err_gt_vector <- function(x1, x2, name1, name2) {
    val <- chk_gt_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_logical_flag
err_is_logical_flag <- function(x, name) {
    val <- chk_is_logical_flag(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_le
err_le_scalar <- function(x1, x2, name1, name2) {
    val <- chk_le_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_le
err_le_vector <- function(x1, x2, name1, name2) {
    val <- chk_le_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_lt
err_lt_scalar <- function(x1, x2, name1, name2) {
    val <- chk_lt_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_lt
err_lt_vector <- function(x1, x2, name1, name2) {
    val <- chk_lt_vector(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_multiple_of
err_multiple_of <- function(x1, x2, name1, name2, null_ok) {
    val <- chk_multiple_of(x1, x2, name1, name2, null_ok)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_multiple_of_n
err_multiple_of_n <- function(x, name, n, null_ok) {
    val <- chk_multiple_of_n(x, name, n, null_ok)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_non_negative
err_non_negative_scalar <- function(x, name) {
    val <- chk_non_negative_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_non_negative
err_non_negative_vector <- function(x, name) {
    val <- chk_non_negative_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_not_equal_integer_scalar
err_not_equal_integer_scalar <- function(x1, x2, name1, name2) {
    val <- chk_not_equal_integer_scalar(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_null
#' @export
err_null_if_null <- function(x1, x2, name1, name2) {
    val <- chk_null_if_null(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_null
#' @export
err_null_onlyif_null <- function(x1, x2, name1, name2) {
    val <- chk_null_onlyif_null(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_null
#' @export
err_null_ifonlyif_null <- function(x1, x2, name1, name2) {
    val <- chk_null_ifonlyif_null(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_positive
err_positive_scalar <- function(x, name) {
    val <- chk_positive_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_positive
err_positive_vector <- function(x, name) {
    val <- chk_positive_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_is_string
err_is_string <- function(x, name) {
    val <- chk_is_string(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_increasing
#' @export
err_increasing <- function(x, name) {
    val <- chk_increasing(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_increasing
#' @export
err_strictly_increasing <- function(x, name) {
    val <- chk_strictly_increasing(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_has_dimnames
err_has_dimnames <- function(x, name) {
    val <- chk_has_dimnames(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_has_dimnames
err_has_names_dimnames <- function(x, name) {
    val <- chk_has_names_dimnames(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_indices_distinct
err_indices_distinct <- function(indices, names, exclude_zero) {
    val <- chk_indices_distinct(indices, names, exclude_zero)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#'@export
#' @rdname chk_length_equals
err_length_equals <- function(x1, x2, name1, name2) {
    val <- chk_length_equals(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_length_same
err_length_same <- function(x1, x2, name1, name2) {
    val <- chk_length_same(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_length_same_or_1
err_length_same_or_1 <- function(x1, x2, name1, name2) {
    val <- chk_length_same_or_1(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_lengths_elements_equal_vec
err_lengths_elements_equal_vec <- function(x1, x2, name1, name2) {
    val <- chk_lengths_elements_equal_vec(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_lt_break_max_age
err_lt_break_max_age <- function(age, break_max, date, dob, unit) {
    val <- chk_lt_break_max_age(age, break_max, date, dob, unit)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_lt_break_max_date
err_lt_break_max_date <- function(date, break_max) {
    val <- chk_lt_break_max_date(date, break_max)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_names_complete
err_names_complete <- function(x, name) {
    val <- chk_names_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_names_dimnames_complete
err_names_dimnames_complete <- function(x, name) {
    val <- chk_names_dimnames_complete(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_pos_initial
err_pos_initial <- function(x, name, zero_ok) {
    val <- chk_pos_initial(x, name, zero_ok)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_positive_dim
err_positive_dim <- function(x, name) {
    val <- chk_positive_dim(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_valid_quantile
err_valid_quantile <- function(x, name) {
    val <- chk_valid_quantile(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_valid_quantile
#' @export
err_quantile_increasing <- function(x, name) {
    val <- chk_quantile_increasing(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_zero
#' @export
err_zero_if_zero <- function(x1, x2, name1, name2) {
    val <- chk_zero_if_zero(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_zero
#' @export
err_zero_onlyif_zero <- function(x1, x2, name1, name2) {
    val <- chk_zero_onlyif_zero(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_zero
#' @export
err_zero_ifonlyif_zero <- function(x1, x2, name1, name2) {
    val <- chk_zero_ifonlyif_zero(x1, x2, name1, name2)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

