## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname member
err_member_time_unit <- function(x, name) {
    val <- chk_member_time_unit(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

