## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname chk_trans_list
err_trans_list <- function(x, name) {
    val <- chk_trans_list(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_map_dim
err_map_dim <- function(map_dim, dim_self, dim_oth) {
    val <- chk_map_dim(map_dim, dim_self, dim_oth)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

