## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname chk_comp_type_indices
err_comp_type_indices <- function(i_comp_type_self, indices_orig_self, i_direction_self) {
    val <- chk_comp_type_indices(i_comp_type_self, indices_orig_self, i_direction_self)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_trans_list
err_trans_list <- function(x, name) {
    val <- chk_trans_list(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_map_dim
err_map_dim <- function(x, name) {
    val <- chk_map_dim(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_map_pos
err_map_pos <- function(x, name) {
    val <- chk_map_pos(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_no_open_age
err_no_open_age <- function(x) {
    val <- chk_no_open_age(x)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_no_open_cohort
err_no_open_cohort <- function(x) {
    val <- chk_no_open_cohort(x)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_open_left_le_break_min
#' @export
err_open_left_le_break_min <- function(labels, int_up, is_open, break_min) {
    val <- chk_open_left_le_break_min(labels, int_up, is_open, break_min)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @rdname chk_open_left_le_break_min
#' @export
err_open_right_ge_break_max <- function(labels, int_low, is_open, break_max) {
    val <- chk_open_right_ge_break_max(labels, int_low, is_open, break_max)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

