## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname chk_values_categories
err_values_categories <- function(x, name) {
    val <- chk_values_categories(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_triangles
err_values_triangles <- function(x, name) {
    val <- chk_values_triangles(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_directions
err_values_directions <- function(x, name) {
    val <- chk_values_directions(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_quantiles
err_values_quantiles <- function(x, name) {
    val <- chk_values_quantiles(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_pairs
err_values_pairs <- function(x, name) {
    val <- chk_values_pairs(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_integers
err_values_integers <- function(x, name) {
    val <- chk_values_integers(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_intervals
err_values_intervals <- function(x, name) {
    val <- chk_values_intervals(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_quantities
err_values_quantities <- function(x, name) {
    val <- chk_values_quantities(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_quarters
err_values_quarters <- function(x, name) {
    val <- chk_values_quarters(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_months
err_values_months <- function(x, name) {
    val <- chk_values_months(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_dateranges
err_values_dateranges <- function(x, name) {
    val <- chk_values_dateranges(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname chk_values_datepoints
err_values_datepoints <- function(x, name) {
    val <- chk_values_datepoints(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

