## This file is generated by the script 'make_err.awk'.
## Do not edit by hand.


#' @export
#' @rdname single
err_has_dimnames <- function(x, name) {
    val <- chk_has_dimnames(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_has_names_dimnames <- function(x, name) {
    val <- chk_has_names_dimnames(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_all_0_1 <- function(x, name) {
    val <- chk_is_all_0_1(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_character <- function(x, name) {
    val <- chk_is_character(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_date <- function(x, name) {
    val <- chk_is_date(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_date_equiv <- function(x, name) {
    val <- chk_is_date_equiv(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_finite_scalar <- function(x, name) {
    val <- chk_is_finite_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_finite_vector <- function(x, name) {
    val <- chk_is_finite_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_integer <- function(x, name) {
    val <- chk_is_integer(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_integer_equiv_scalar <- function(x, name) {
    val <- chk_is_integer_equiv_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_integer_equiv_vector <- function(x, name) {
    val <- chk_is_integer_equiv_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_length_1 <- function(x, name) {
    val <- chk_is_length_1(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_logical <- function(x, name) {
    val <- chk_is_logical(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_not_na_dataframe <- function(x, name) {
    val <- chk_is_not_na_dataframe(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_not_na_list <- function(x, name) {
    val <- chk_is_not_na_list(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_not_na_scalar <- function(x, name) {
    val <- chk_is_not_na_scalar(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_not_na_vector <- function(x, name) {
    val <- chk_is_not_na_vector(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_numeric <- function(x, name) {
    val <- chk_is_numeric(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_is_positive_length <- function(x, name) {
    val <- chk_is_positive_length(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

#' @export
#' @rdname single
err_no_dimnames <- function(x, name) {
    val <- chk_no_dimnames(x, name)
    if (is.character(val))
        stop(val, call. = FALSE)
    TRUE
}

